// all the emotions for the check-in page
export const emotions = [
  { name: 'Happy', emoji: '😊' },
  { name: 'Grateful', emoji: '🙏' },
  { name: 'Calm', emoji: '😌' },
  { name: 'Hopeful', emoji: '🌱' },
  { name: 'Energetic', emoji: '⚡' },
  { name: 'Loved', emoji: '💜' },
  { name: 'Brave', emoji: '💪' },
  { name: 'Satisfied', emoji: '😊' },
  { name: 'Proud', emoji: '🏆' },
  { name: 'Excited', emoji: '🎉' },
  { name: 'Motivated', emoji: '🔥' },
  { name: 'Relaxed', emoji: '🧘' },
  { name: 'Anxious', emoji: '😰' },
  { name: 'Sad', emoji: '😢' },
  { name: 'Angry', emoji: '😤' },
  { name: 'Overwhelmed', emoji: '🌊' },
  { name: 'Lonely', emoji: '🫂' },
  { name: 'Exhausted', emoji: '😮‍💨' },
  { name: 'Stressed', emoji: '😫' },
  { name: 'Worried', emoji: '😟' },
  { name: 'Annoyed', emoji: '😒' },
  { name: 'Unmotivated', emoji: '😴' },
  { name: 'Fine', emoji: '🙂' },
  { name: 'Busy', emoji: '🏃' },
  { name: 'Confused', emoji: '🤔' },
  { name: 'Restless', emoji: '🔄' },
  { name: 'Bored', emoji: '😐' },
  { name: 'Numb', emoji: '😶' },
  { name: 'Embarrassed', emoji: '😳' },
  { name: 'Let down', emoji: '😞' },
  { name: 'Nervous', emoji: '😬' },
];
