import { Request, Response, NextFunction } from 'express';
import { moodEntryRepository } from '../repositories/mood-entry.repository.js';
import { journalRepository } from '../repositories/journal.repository.js';
import { checkInRepository } from '../repositories/check-in.repository.js';

export const exportController = {
  async csv(req: Request, res: Response, next: NextFunction) {
    try {
      const moods = await moodEntryRepository.findByUser(req.user!.userId, 1000);

      const csvHeader = 'Date,Rating,Emotions,Note,Source\n';
      const csvRows = moods.map((m) =>
        [
          new Date(m.recorded_at).toISOString().split('T')[0],
          m.rating,
          `"${m.emotion_tags.join(', ')}"`,
          `"${(m.note || '').replace(/"/g, '""')}"`,
          m.source,
        ].join(',')
      );

      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', 'attachment; filename=mymind-mood-data.csv');
      res.send(csvHeader + csvRows.join('\n'));
    } catch (err) {
      next(err);
    }
  },

  async therapistSummary(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = req.user!.userId;
      const [moods, streak, emotions, journals] = await Promise.all([
        moodEntryRepository.findByUser(userId, 30),
        checkInRepository.getStreak(userId),
        moodEntryRepository.getEmotionBreakdown(userId, 30),
        journalRepository.findByUser(userId, 10),
      ]);

      const avgMood = moods.length > 0
        ? (moods.reduce((s, m) => s + m.rating, 0) / moods.length).toFixed(1)
        : 'N/A';

      const summary = {
        generatedAt: new Date().toISOString(),
        period: 'Last 30 days',
        overview: {
          totalCheckIns: moods.length,
          averageMood: avgMood,
          currentStreak: streak,
          topEmotions: emotions.slice(0, 5),
        },
        moodEntries: moods.map((m) => ({
          date: new Date(m.recorded_at).toISOString().split('T')[0],
          rating: m.rating,
          emotions: m.emotion_tags,
          note: m.note,
        })),
        journalEntryCount: journals.length,
        disclaimer: 'This summary was generated by My Mind and is intended to supplement, not replace, clinical assessment.',
      };

      res.json(summary);
    } catch (err) {
      next(err);
    }
  },
};
